### ISSUE TITLE
Hundreds of NEW sources in image extraction with OSA11.1

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/frontend-astrooda#61] opened 2021-07-03 08:26 UTC
I tried to extract images with OSA 11, detection threshold 5. This gives hundreds of "NEW" sources, this is at least inconvenient, and image display looks ugly. Is this normal?

from oda_api.api import DispatcherAPI

disp = DispatcherAPI(
url="https://frontend.staging.odahub.io/cdci/astrooda//dispatch-data", instrument="mock"
)

par_dict = {
"DEC": "61.229221",
"E1_keV": "20",
"E2_keV": "40",
"RA": "40.131944",
"T1": "2019-01-01T00:00:00.0",
"T2": "2020-01-01T00:00:00.0",
"T_format": "isot",
"detection_threshold": "5",
"instrument": "isgri",
"integral_data_rights": "public",
"max_pointings": "50",
"osa_version": "OSA11.1",
"product": "isgri_image",
"product_type": "Real",
"radius": "15",
"src_name": "LSI +61 303",
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbmRyaWkuTmVyb25vdkB1bmlnZS5jaCIsImVtYWlsIjoiQW5kcmlpLk5lcm9ub3ZAdW5pZ2UuY2giLCJuYW1lIjoiYW5lcm9ub3YiLCJyb2xlcyI6ImF1dGhlbnRpY2F0ZWQgdXNlciwgY29udGVudCBtYW5hZ2VyIiwiZXhwIjoxNjI1MjcyMDYzfQ.SeKduuwR4ItgATcOVp7lL7MTkk_QZe5XqRX50ryC-O8",
}

data_collection = disp.get_product(**par_dict)

**Comment by volodymyrss** [comment] 2021-07-03 18:38
most likely because of 20 keV start. Please start at least from 25. Better 30. Spectra are validated from 35.

**Comment by ferrigno** [comment] 2021-07-04 15:29
I was about to leave the same comment: in QLA, we chose 28 keV to optimize sensitivity vs noise.We do not consider any source below 7 sigma as serious candidate.
We might consider changing the defaults:
detection threshold 7 for both ISGRI and JEM-X, minimum energy 28 keV for ISGRI with OSA11. 
Maximum energy 20 keV for JEM-X.

**Comment by volodymyrss** [comment] 2021-07-04 18:16
@burnout87 could easily do this, I think, if he could please

**Comment by burnout87** [comment] 2021-07-05 08:54
This is a duplicate of

[https://github.com/oda-hub/frontend-astrooda/issues/62](urlhttps://github.com/oda-hub/frontend-astrooda/issues/62)

**Closed by burnout87** 2021-07-05 08:54 UTC
Labels: Feature

**Comment by volodymyrss** [comment] 2021-07-05 09:04
https://github.com/oda-hub/frontend-astrooda/issues/62 is follow-up of this one, not exactly a duplicate. Once we change defaults @andriineronov needs to confirm it fixes the problem. 

I think in this case, @andriineronov already checked with different energy range, and probably was satisfied.
Please @andriineronov reopen this issue of hundreds of sources remain in different energy range.
